name: travelitin_services
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.7.0
  shared_preferences: ^2.3.0
  permission_handler: ^12.0.0+1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  lints: ^6.0.0
  material_color_utilities: ^0.12.0
  meta: ^1.17.0
  vector_math: ^2.1.5
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.10
  leak_tracker_testing: ^3.0.2
  test_api: ^0.7.6
  vm_service: ^15.0.0
