// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAgXyPScajYOx5HfeS-X_8cA3nEUAMk-U',
    appId: '1:298326883117:web:83262acefa3818d13231a4',
    messagingSenderId: '298326883117',
    projectId: 'asafetyguide-369ee',
    authDomain: 'asafetyguide-369ee.firebaseapp.com',
    storageBucket: 'asafetyguide-369ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArQdgXuY_rB6YbrRMdjBjeC3Wkp-jMfTA',
    appId: '1:298326883117:android:fa5f353622b459d63231a4',
    messagingSenderId: '298326883117',
    projectId: 'asafetyguide-369ee',
    storageBucket: 'asafetyguide-369ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICcfy7km38GBfo4pfWwNFymwk0IIaQOg',
    appId: '1:298326883117:ios:3089c6d42704ebe83231a4',
    messagingSenderId: '298326883117',
    projectId: 'asafetyguide-369ee',
    storageBucket: 'asafetyguide-369ee.firebasestorage.app',
    iosBundleId: 'com.example.thingqbator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAICcfy7km38GBfo4pfWwNFymwk0IIaQOg',
    appId: '1:298326883117:ios:3089c6d42704ebe83231a4',
    messagingSenderId: '298326883117',
    projectId: 'asafetyguide-369ee',
    storageBucket: 'asafetyguide-369ee.firebasestorage.app',
    iosBundleId: 'com.example.thingqbator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAgXyPScajYOx5HfeS-X_8cA3nEUAMk-U',
    appId: '1:298326883117:web:7fe7962605c6f5a83231a4',
    messagingSenderId: '298326883117',
    projectId: 'asafetyguide-369ee',
    authDomain: 'asafetyguide-369ee.firebaseapp.com',
    storageBucket: 'asafetyguide-369ee.firebasestorage.app',
  );

}