name: travelitin
description: A travel planning and management application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  http: ^1.2.2
  provider: ^6.1.2
  webview_flutter: ^4.0.0
  flutter_inappwebview: ^6.1.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.13.6
  firebase_database: ^10.3.8
  firebase_storage: ^11.5.6
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.10
  pin_code_fields: ^8.0.1
  get: ^4.6.6
  pinput: ^5.0.0
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.0.0
  carousel_slider: ^5.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.20.1       # For date formatting
  flutter_markdown: ^0.7.4+3
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1
  glassmorphism: ^3.0.0
  animate_do: ^3.3.4
  speech_to_text: ^7.0.0
  translator: ^1.0.3+1
  flutter_tts: ^4.2.1
  flutter_typeahead: ^5.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  url_launcher: ^6.0.20
  marquee: ^2.1.0
  bootstrap_icons: ^1.11.3
  flutter_keyboard_visibility: ^6.0.0
  flutter_fireworks: ^1.0.8
  flutter_animate: ^4.5.2
  go_router: ^13.0.0
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/carousel/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: OliveVillage
      fonts:
        - asset: assets/fonts/OliveVillage-Regular.ttf