name: travelitin
description: "Asafetyguide"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.0.6
  http: ^1.2.2
  provider: ^6.1.2
  webview_flutter: ^4.0.0
  flutter_inappwebview: ^6.1.5
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.0.0
  firebase_database: ^11.2.0
  firebase_storage: ^12.3.7
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.10
  pin_code_fields: ^8.0.1
  get: ^4.6.6
  pinput: ^5.0.0
  shared_preferences: ^2.1.0
  intl_phone_field: ^3.0.0
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.20.1
  flutter_markdown: ^0.7.4+3
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.2.1
  glassmorphism: ^3.0.0
  animate_do: ^3.3.4
  speech_to_text: ^7.0.0
  translator: ^1.0.3+1
  flutter_tts: ^4.2.1
  flutter_typeahead: ^4.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  url_launcher: ^6.0.20
  marquee: ^2.1.0
  bootstrap_icons: ^1.11.3
  flutter_keyboard_visibility: ^5.4.1
  flutter_fireworks: ^1.0.8
  flutter_animate: ^4.5.2
  go_router: ^14.8.0
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_driver:
    sdk: flutter
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/carousel/
    - assets/
    - assets/animations/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
    - family: OliveVillage
      fonts:
        - asset: assets/fonts/OliveVillage-Regular.ttf
        - asset: assets/fonts/OliveVillage-Italic.ttf
          style: italic
    - family: CalSans
      fonts:
        - asset: assets/fonts/CalSans-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true
  web: false